// <auto-generated />
namespace NovelHelper_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCharaters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCharaters));
        
        string IMigrationMetadata.Id
        {
            get { return "201705101843507_AddCharaters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
